# config/packages/doctrine_migrations.yaml
doctrine_migrations:
  migrations_paths:
    # Namespace rÃƒÂ©servÃƒÂ© aux migrations Doctrine (ne pas utiliser App\Ã¢â‚¬Â¦)
    'DoctrineMigrations': '%kernel.project_dir%/migrations'

  # AtomicitÃƒÂ© : une migration ÃƒÂ©choue Ã¢â€ â€™ rollback complet
  all_or_nothing: true

  # Classement automatique des migrations dans des sous-dossiers (annÃƒÂ©e/mois)
  organize_migrations: BY_YEAR_AND_MONTH

  # DÃƒÂ©sactivÃƒÂ© en prod pour ÃƒÂ©viter les surcharges
  enable_profiler: false
