# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # dÃƒÂ©sactive totalement les annotations (routes, etc.)
    annotations: false

    # EmpÃƒÂªche les overrides HTTP type _method
    http_method_override: false

    # Intercepte toutes les erreurs PHP (y compris fatales)
    handle_all_throwables: true

    # Protection CSRF activÃƒÂ©e globalement (sÃƒÂ©curitÃƒÂ© des formulaires)
    csrf_protection: true

    # Sessions
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Journalisation des erreurs PHP
    php_errors:
        log: true

# Configuration spÃƒÂ©cifique ÃƒÂ  lÃ¢â‚¬â„¢environnement de test
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
