# config/packages/liip_imagine.yaml
liip_imagine:
  driver: 'gd'

  twig:
    mode: lazy

  resolvers:
    default:
      web_path: ~

  filter_sets:
    cache: ~

    listing_card:
      quality: 90
      filters:
        thumbnail:
          size: [400, 225]
          mode: inset      # ✔ NE COUPE PLUS L’IMAGE
          allow_upscale: true

    listing_show:
      quality: 90
      filters:
        thumbnail:
          size: [1200, 675]
          mode: inset      # ✔ garde l’image entière
          allow_upscale: true

    avatar_thumb:
      quality: 90
      filters:
        thumbnail:
          size: [100, 100]
          mode: inset
          allow_upscale: true
