framework:
  mailer:
    dsn: '%env(MAILER_DSN)%'

    # Par d√©faut, Symfony utilise text brut si pas de template.
    # On ajoute les chemins vers nos templates Twig
    envelope:
      sender: 'no-reply@talenteko.test'

twig:
  paths:
    '%kernel.project_dir%/templates/emails': emails
