# config/packages/mailer.yaml
framework:
  mailer:
    dsn: '%env(MAILER_DSN)%'

    # ExpÃƒÆ’Ã‚Â©diteur par dÃƒÆ’Ã‚Â©faut (variable d'environnement)
    envelope:
      sender: '%env(APP_MAILER_FROM)%'


