# config/packages/security.yaml
security:
  # --- Hashage des mots de passe ---
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # --- Provider utilisateur (auth via email) ---
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # --- Firewalls ---
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: / # Redirection aprÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¨s dÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©connexion

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 1 semaine
        path: /
        # always_remember_me: true activer seulement si souhaitÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©

  # --- rÃ¨gles d'accÃ¨s (ordre ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©valuÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â© de haut en bas) ---
  access_control:
    # Pages publiques
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/inscription$, roles: PUBLIC_ACCESS }
    - { path: ^/uploads/listings, roles: PUBLIC_ACCESS } #

    # Pages statiques
    - { path: ^/faq, roles: PUBLIC_ACCESS }
    - { path: ^/a-propos, roles: PUBLIC_ACCESS }
    - { path: ^/mentions-legales, roles: PUBLIC_ACCESS }
    - { path: ^/contact, roles: PUBLIC_ACCESS }

    # Admin & styleguide
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/styleguide, roles: ROLE_ADMIN }

    # Tout le reste nÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©cessite une authentification complÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¨te
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

# --- config spÃ©cifique
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
    firewalls:
      main:
        remember_me: false # DÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©sactivÃ© en test




