# config/packages/security.yaml
security:
  # --- Hashage des mots de passe ---
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # --- Provider utilisateur (auth via email) ---
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # --- Firewalls ---
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: /  # redirection après déconnexion

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800   # 1 semaine
        path: /
        # always_remember_me: true

  # --- Règles d'accès (ordre évalué de haut en bas) ---
  access_control:
    # Pages publiques (visibles sans compte)
    - { path: ^/$, roles: PUBLIC_ACCESS }                  # Accueil
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/inscription$, roles: PUBLIC_ACCESS }
    - { path: ^/uploads/listings, roles: PUBLIC_ACCESS }   # Vignettes des annonces migre les images sensibles (photos de personnes) vers un dossier privé et placeholders publiques

    # Pages statiques (footer)
    - { path: ^/faq, roles: PUBLIC_ACCESS }
    - { path: ^/a-propos, roles: PUBLIC_ACCESS }
    - { path: ^/mentions-legales, roles: PUBLIC_ACCESS }
    - { path: ^/contact, roles: PUBLIC_ACCESS }

    # Admin & styleguide (réservés aux admins)
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/styleguide, roles: ROLE_ADMIN }

    # Tout le reste nécessite un compte (utilisateur inscrit)
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
    firewalls:
      main:
        remember_me: false  # désactivé en test
