security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator

      logout:
        path: app_logout
        target: /

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /

  access_control:
    # Pages publiques
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/login$, roles: PUBLIC_ACCESS }
    - { path: ^/logout$, roles: PUBLIC_ACCESS }
    - { path: ^/inscription$, roles: PUBLIC_ACCESS }
    - { path: ^/uploads/listings, roles: PUBLIC_ACCESS }

    # Mot de passe oublié — PUBLIC
    - { path: ^/reset-password/request$, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password/, roles: PUBLIC_ACCESS }

    # Pages statiques
    - { path: ^/faq, roles: PUBLIC_ACCESS }
    - { path: ^/a-propos, roles: PUBLIC_ACCESS }
    - { path: ^/mentions-legales, roles: PUBLIC_ACCESS }
    - { path: ^/contact, roles: PUBLIC_ACCESS }

    # Admin
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/styleguide, roles: ROLE_ADMIN }

    # Listing protégés
    - { path: ^/listing/nouvelle, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/listing/.+/edit, roles: IS_AUTHENTICATED_FULLY }

    # Le reste → user connecté (remember me OK)
    - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
