twig:
  default_path: '%kernel.project_dir%/templates'
  file_name_pattern: '*.twig'
  charset: 'UTF-8'

  paths:
    '%kernel.project_dir%/templates/exchange': exchange

when@test:
  twig:
    strict_variables: true
