twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    charset: 'UTF-8'   # For√ßage explicite

    # Ajout des chemins custom
    paths:
        '%kernel.project_dir%/templates/emails': emails

when@test:
    twig:
        strict_variables: true
